apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nyx-prod
resources:
  - ../../base
  - namespace.yaml
  - pod-disruption-budget.yaml
patches:
  - path: deployment-patch.yaml
labels:
  - pairs:
      app.kubernetes.io/name: nyx-api
      app.kubernetes.io/instance: nyx-prod
      app.kubernetes.io/part-of: nyx
      app.kubernetes.io/managed-by: platform
    includeSelectors: true
    includeTemplates: true
commonAnnotations:
  metacortex.io/owner: team-nyx
  metacortex.io/runbook: https://runbooks.metacortex.io/nyx/api
